title: jekyll-theme-giellalt
description: Shared Jekyll theme for GiellaLT documentation sites.

theme: jekyll-theme-giellalt

plugins:
  - jekyll-theme-giellalt

exclude:
  - README.md
  - LICENSE
  - jekyll-theme-giellalt.gemspec
  - lib
  - vendor
