require "jekyll-theme-giellalt/version"

require "jekyll-seo-tag"
require "jekyll-github-metadata"
require "jekyll-include-cache"
require "jemoji"
require "jekyll-optional-front-matter"
require "jekyll-redirect-from"
require "jekyll-relative-links"
require "jekyll-titles-from-headings"
require "jekyll-default-layout"
require "jekyll-readme-index"
require "jekyll-sitemap"
require "jekyll-gist"
require "jekyll-minifier" if ENV["JEKYLL_ENV"] == "production"
